create table if not exists public.area_map_versions (
  id uuid primary key default gen_random_uuid(),
  version_no bigint generated by default as identity unique,
  deployment_context text not null default 'production',
  status text not null default 'draft'
    check (status in ('draft', 'validated', 'published', 'rejected', 'archived')),
  source_version_id uuid references public.area_map_versions(id) on delete restrict,
  original_file_name text not null,
  raw_storage_path text,
  processed_storage_path text,
  sha256 text not null check (sha256 ~ '^[0-9a-f]{64}$'),
  file_size_bytes bigint not null check (file_size_bytes > 0 and file_size_bytes <= 3145728),
  feature_count integer not null default 0 check (feature_count >= 0),
  matched_count integer not null default 0 check (matched_count >= 0),
  unmatched_count integer not null default 0 check (unmatched_count >= 0),
  master_without_map_count integer not null default 0 check (master_without_map_count >= 0),
  duplicate_count integer not null default 0 check (duplicate_count >= 0),
  conflict_count integer not null default 0 check (conflict_count >= 0),
  bounds jsonb not null default '[]'::jsonb,
  source_metadata jsonb not null default '{}'::jsonb,
  reconciliation_summary jsonb not null default '{}'::jsonb,
  validation_errors jsonb not null default '[]'::jsonb,
  unmatched_acknowledged boolean not null default false,
  uploaded_by_profile_id uuid references public.profiles(id) on delete set null,
  published_by_profile_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  published_at timestamptz,
  archived_at timestamptz,
  constraint area_map_versions_storage_paths check (
    (status in ('draft', 'rejected'))
    or (raw_storage_path is not null and processed_storage_path is not null)
  )
);

comment on table public.area_map_versions is
  'Immutable KMZ/processed GeoJSON version metadata. Canonical business identity remains public.blocks.id.';
comment on column public.area_map_versions.deployment_context is
  'Server-derived context (production or isolated preview/UAT branch) so preview publication cannot change the production active map.';

create unique index if not exists ux_area_map_versions_one_published_context
  on public.area_map_versions (deployment_context)
  where status = 'published';
create index if not exists area_map_versions_context_version_idx
  on public.area_map_versions (deployment_context, version_no desc);
create index if not exists area_map_versions_source_version_idx
  on public.area_map_versions (source_version_id)
  where source_version_id is not null;

alter table public.area_map_versions enable row level security;
revoke all on table public.area_map_versions from anon, authenticated;
grant select, insert, update on table public.area_map_versions to service_role;
grant usage, select on sequence public.area_map_versions_version_no_seq to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'area-map-files',
  'area-map-files',
  false,
  12582912,
  array['application/vnd.google-earth.kmz', 'application/zip', 'application/octet-stream', 'application/geo+json', 'application/json']
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

with desired(permission_key, permission_name, module_key, action_key, description) as (
  values
    ('farm.area_map.manage', 'Manage Area KMZ drafts', 'farm', 'area_map_manage', 'Upload, validate, preview, and reject Area KMZ versions'),
    ('farm.area_map.publish', 'Publish Area KMZ', 'farm', 'area_map_publish', 'Publish a validated Area KMZ version'),
    ('farm.area_map.rollback', 'Rollback Area KMZ', 'farm', 'area_map_rollback', 'Create and publish an immutable rollback version')
)
insert into public.permissions (
  code, name, module, action, description,
  permission_key, permission_name, module_key, action_key, status
)
select
  permission_key, permission_name, module_key, action_key, description,
  permission_key, permission_name, module_key, action_key, 'active'
from desired d
where not exists (
  select 1 from public.permissions p
  where p.permission_key = d.permission_key or p.code = d.permission_key
);

with desired(role_key, permission_key) as (
  values
    ('super_admin', 'farm.area_map.manage'),
    ('super_admin', 'farm.area_map.publish'),
    ('super_admin', 'farm.area_map.rollback'),
    ('director', 'farm.area_map.manage'),
    ('director', 'farm.area_map.publish'),
    ('director', 'farm.area_map.rollback'),
    ('manager', 'farm.area_map.manage'),
    ('manager', 'farm.area_map.publish'),
    ('manager', 'farm.area_map.rollback'),
    ('uat_manager', 'farm.area_map.manage'),
    ('uat_manager', 'farm.area_map.publish'),
    ('uat_manager', 'farm.area_map.rollback')
)
insert into public.role_permissions (role_id, permission_id, is_allowed, status)
select r.id, p.id, true, 'active'
from desired d
join public.roles r on r.role_key = d.role_key and r.status = 'active'
join public.permissions p on p.permission_key = d.permission_key and p.status = 'active'
on conflict (role_id, permission_id)
  where role_id is not null and permission_id is not null
do update set is_allowed = true, status = 'active';

create or replace function public.publish_area_map_version(
  p_version_id uuid,
  p_deployment_context text,
  p_actor_profile_id uuid
)
returns public.area_map_versions
language plpgsql
security invoker
set search_path = ''
as $$
declare
  target public.area_map_versions;
begin
  if nullif(trim(p_deployment_context), '') is null then
    raise exception using errcode = '22023', message = 'deployment context is required';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('area-map:' || p_deployment_context, 0));

  select * into target
  from public.area_map_versions
  where id = p_version_id and deployment_context = p_deployment_context
  for update;

  if target.id is null then
    raise exception using errcode = 'P0002', message = 'Area map version not found';
  end if;
  if target.status = 'published' then
    return target;
  end if;
  if target.status <> 'validated' then
    raise exception using errcode = '22023', message = 'Only a validated Area map version can be published';
  end if;
  if target.feature_count <= 0
     or target.processed_storage_path is null
     or jsonb_typeof(target.bounds) <> 'array'
     or jsonb_array_length(target.bounds) <> 4
     or jsonb_typeof(target.validation_errors) <> 'array'
     or jsonb_array_length(target.validation_errors) > 0
     or target.duplicate_count > 0
     or target.conflict_count > 0
     or (target.unmatched_count > 0 and not target.unmatched_acknowledged) then
    raise exception using errcode = '22023', message = 'Area map version does not pass the publish gate';
  end if;

  update public.area_map_versions
  set status = 'archived', archived_at = now()
  where deployment_context = p_deployment_context and status = 'published' and id <> target.id;

  update public.area_map_versions
  set status = 'published',
      published_by_profile_id = p_actor_profile_id,
      published_at = now(),
      archived_at = null
  where id = target.id
  returning * into target;

  return target;
end;
$$;

create or replace function public.rollback_area_map_version(
  p_source_version_id uuid,
  p_deployment_context text,
  p_actor_profile_id uuid,
  p_reason text default null
)
returns public.area_map_versions
language plpgsql
security invoker
set search_path = ''
as $$
declare
  source public.area_map_versions;
  restored public.area_map_versions;
begin
  if nullif(trim(p_deployment_context), '') is null then
    raise exception using errcode = '22023', message = 'deployment context is required';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('area-map:' || p_deployment_context, 0));

  select * into source
  from public.area_map_versions
  where id = p_source_version_id and deployment_context = p_deployment_context
  for update;

  if source.id is null then
    raise exception using errcode = 'P0002', message = 'Rollback source version not found';
  end if;
  if source.processed_storage_path is null
     or source.feature_count <= 0
     or jsonb_typeof(source.validation_errors) <> 'array'
     or jsonb_array_length(source.validation_errors) > 0
     or source.duplicate_count > 0
     or source.conflict_count > 0 then
    raise exception using errcode = '22023', message = 'Rollback source is not a valid published artifact';
  end if;

  insert into public.area_map_versions (
    deployment_context, status, source_version_id, original_file_name,
    raw_storage_path, processed_storage_path, sha256, file_size_bytes,
    feature_count, matched_count, unmatched_count, master_without_map_count,
    duplicate_count, conflict_count, bounds, source_metadata,
    reconciliation_summary, validation_errors, unmatched_acknowledged,
    uploaded_by_profile_id
  ) values (
    p_deployment_context, 'validated', source.id, source.original_file_name,
    source.raw_storage_path, source.processed_storage_path, source.sha256, source.file_size_bytes,
    source.feature_count, source.matched_count, source.unmatched_count, source.master_without_map_count,
    source.duplicate_count, source.conflict_count, source.bounds,
    source.source_metadata || jsonb_build_object(
      'rollbackOfVersionId', source.id,
      'rollbackOfVersionNo', source.version_no,
      'rollbackReason', coalesce(p_reason, '')
    ),
    source.reconciliation_summary, source.validation_errors, true,
    p_actor_profile_id
  )
  returning * into restored;

  update public.area_map_versions
  set status = 'archived', archived_at = now()
  where deployment_context = p_deployment_context and status = 'published';

  update public.area_map_versions
  set status = 'published',
      published_by_profile_id = p_actor_profile_id,
      published_at = now(),
      archived_at = null
  where id = restored.id
  returning * into restored;

  return restored;
end;
$$;

revoke all on function public.publish_area_map_version(uuid, text, uuid) from public, anon, authenticated;
revoke all on function public.rollback_area_map_version(uuid, text, uuid, text) from public, anon, authenticated;
grant execute on function public.publish_area_map_version(uuid, text, uuid) to service_role;
grant execute on function public.rollback_area_map_version(uuid, text, uuid, text) to service_role;
